name: CI

on:
  push:
    branches:
      [main, chore/add-coverage-and-improve-tests]
  pull_request:
    branches:
      main

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        run: xcodebuild -scheme PolywrapClient -destination 'platform=macOS' -enableCodeCoverage YES clean build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3