name: Cocoapods CI

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint library
        run: pod spec lint --verbose --allow-warnings
