name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - chore/docs

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate cases
        run: |
          cd Scripts
          ./generate_cases.sh

      - name: Build docs
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 5
          command: ./Scripts/build_docs.sh

      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download docs
        uses: actions/download-artifact@v2
        with:
          name: docs

      - name: Move docs to new directory
        run: |
          mkdir new_docs
          mv docs new_docs/

      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: new_docs
