name: Examples CI

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  examples:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build examples
        run: ./Scripts/run_examples.sh
