name: Swift Package Manager CI

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate cases
        run: |
          cd Scripts
          ./generate_cases.sh

      - name: Build
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 5
          command: xcodebuild -scheme PolywrapClient -derivedDataPath Build/ -destination 'platform=macOS' clean build

      - name: Test
        run: xcodebuild -scheme PolywrapClient -derivedDataPath Build/ -destination 'platform=macOS' -enableCodeCoverage YES test

      - name: Generate Coverage Info
        run: |
          cd Build/Build/ProfileData
          cd $(ls -d */|head -n 1)
          directory=${PWD##*/}
          pathCoverage=Build/Build/ProfileData/${directory}/Coverage.profdata
          cd ../../../../
          xcrun llvm-cov export -format="lcov" -instr-profile $pathCoverage Build/Build/Products/Debug/PolywrapClient.o > cov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cov.info
